#lang planet neil/sicp
(define (make-account balance password)
  (define (withdraw amount)
    (if (>= balance amount) 
        (begin (set! balance (- balance amount)) balance)
        "Insufficient funds"))
  (define (deposit amount)
    (set! balance (+ balance amount))
    balance)
  (define dispatch 
    (let ((errcnt 0))
     (lambda (pw m)
       (if (<= errcnt 7)
           (if (eq? pw password)
               (cond ((eq? m 'withdraw) withdraw)
                     ((eq? m 'deposit) deposit)
                     (else (error "Unkown request -- MAKE-ACCOUNT" m)))
               (lambda (m) (set! errcnt (+ errcnt 1)) "password error"))
           (lambda (m) "call cop")
           ))))
  dispatch)

(define acc (make-account 100 'sai))
((acc 'sai 'withdraw) 10)
((acc 'sai 'deposit) 10)

((acc 'sai1 'withdraw) 10)
((acc 'sai1 'withdraw) 10)
((acc 'sai1 'withdraw) 10)
((acc 'sai1 'withdraw) 10)
((acc 'sai1 'withdraw) 10)
((acc 'sai1 'withdraw) 10)
((acc 'sai1 'withdraw) 10)
((acc 'sai1 'withdraw) 10)

((acc 'sai 'withdraw) 10)
((acc 'sai 'deposit) 10)