#lang planet neil/sicp
(define (make-account balance password)
  (define (withdraw amount)
    (if (>= balance amount) 
        (begin (set! balance (- balance amount)) balance)
        "Insufficient funds"))
  (define (deposit amount)
    (set! balance (+ balance amount))
    balance)
  (define (dispatch pw m)
    (if (eq? pw password)
        (cond ((eq? m 'withdraw) withdraw)
              ((eq? m 'deposit) deposit)
              (else (error "Unkown request -- MAKE-ACCOUNT" m)))
        (lambda (m) "password error")))
  dispatch)

(define acc (make-account 100 'sai))
((acc 'sai1 'withdraw) 10)
((acc 'sai 'withdraw) 10)
((acc 'sai 'deposit) 10)